name: Build

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request_review' || github.event.review.state == 'approved'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Set up Pico SDK
      run: |
        # Install dependencies
        sudo apt-get update &&
        sudo apt install \
          cmake python3 build-essential \
          gcc-arm-none-eabi \
          libnewlib-arm-none-eabi \
          libstdc++-arm-none-eabi-newlib

        # Download and set up Pico SDK
        cd $HOME
        git clone https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init

        echo "PICO_SDK_PATH=$HOME/pico-sdk" >> $GITHUB_ENV

    - name: Build firmware
      run: |
        cmake . -DPICO_SDK_PATH=$PICO_SDK_PATH
        make -j$(nproc)

    - name: Verify build artifacts
      run: |
        echo "Build artifacts:"
        find . -name "*.uf2" -o -name "*.bin" -o -name "*.elf" -o -name "*.hex" | head -10

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          *.uf2
        retention-days: 30
